trigger:
- master
pr:
- master
pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage  
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: PowerShell@2
      inputs:
        filePath: '$(System.DefaultWorkingDirectory)/.azure-pipeline/gitdiff.ps1'
        arguments: '$(Build.SourceVersion)'    
    - task: PowerShell@2
      inputs:
        filePath: '$(System.DefaultWorkingDirectory)/.azure-pipeline/ymlparser.ps1'
        arguments: $(System.DefaultWorkingDirectory) $(yamlFileName)
    - task: PowerShell@2
      inputs:
        filePath: '$(System.DefaultWorkingDirectory)/.azure-pipeline/accounttypeselector.ps1'
        arguments: $(cloud)